kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-app-pvc
  namespace: sample-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
