apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
  namespace: sample-app
spec:
      workspaces:     
        - name: shared-workspace
      # pipeline params   
      params:
      - name: branch-name
        type: string
        description: The git branch to clone.
      - name: image-tag
        type: string
        description: repo image tag  
      #list of tasks   
      tasks:
      - name: clone
        taskRef:
          name: git-clone
        workspaces:
            - name: output
              workspace: shared-workspace 
        params:
          - name: url
            value: https://github.com/vinay-nandipur/buildbot-tekton
          - name: revision 
            value: "$(params.branch-name)"  
          - name: subdirectory
            value: "sample-app"
          - name: deleteExisting
            value: "true"
          - name: sslVerify
            value: "false"
      - name: build
        taskRef:
          name: s2i
        runAfter:
          - clone
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: BUILDER_IMAGE
            value: quay.io/centos7/python-38-centos7
          - name: TLSVERIFY
            value: "false"
          - name: LOGLEVEL
            value: "10"
          - name: IMAGE_NAME
            value: localhost:5000/sample-app:latest
      # in any case run this 
      finally: 
      - name: slack-final-notification
        taskRef:
          name: send-to-webhook-slack
        when: 
        - input: "$(tasks.status)"
          operator: in
          values: ["Completed","Failed","Succeeded"]   
        params:
          - name: webhook-secret
            value: slack-webhook-secret
          - name: message
            value: "build bot pipeline *$(tasks.status)* for branch: $(params.branch-name)" 
