kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-app-pvc
  namespace: sample-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-app-build-
  namespace: sample-app
spec:
  serviceAccountName: sample-app-sa  
  pipelineRef:
    name: build-pipeline

  params:
    - name: branch-name
      value: "main"  
    - name: image-tag
      value: "v1"   
      
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: sample-app-pvc
        
