apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-pipeline-template
spec:
  params:
  - name: branch 
  - name: image    

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-pipeline-from-slack-
      namespace: sample-app
      labels:
        tekton.dev/pipeline: build-pipeline 
    spec:     
        params:
        - name: branch-name
          value: $(tt.params.branch)
        - name: image-tag
          value: $(tt.params.image)      

        pipelineRef:
          name: build-pipeline
        serviceAccountName: sample-app-sa 
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: sample-app-pvc

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: builder-bot-listener-interceptor
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: sample-app-sa
  triggers:    
    - name: slack-bot-build-trigger
      interceptors:
        - ref:
            name: "slack"
            kind: ClusterInterceptor
          params:
            - name: requestedFields
              value:
                - text
        - ref:
            name: cel
          params:
          - name: "overlays"
            value:
              - key: branch
                expression: 'extensions.text.split(" ")[0]'
              - key: image
                expression: 'extensions.text.split(" ")[1]'
      bindings:
        - name: branch
          value: $(extensions.branch)
        - name: image
          value: $(extensions.image)
      template:
          ref: build-pipeline-template

